// frontend
export { default as accessibility } from './frontend/accessibility.json'
export { default as angular } from './frontend/angular.json'
export { default as animations } from './frontend/animations.json'
export { default as colors } from './frontend/colors.json'
export { default as cssGames } from './frontend/css_games.json'
export { default as fonts } from './frontend/fonts.json'
export { default as icons } from './frontend/icons.json'
export { default as illustrations } from './frontend/illustrations.json'
export { default as images } from './frontend/images.json'
export { default as onlineCodeEditors } from './frontend/online_code_editors.json'
export { default as themesTemplates } from './frontend/themes_and_templates.json'
export { default as uiGenerators } from './frontend/ui_generators.json'
export { default as react } from './frontend/react.json'
export { default as next } from './frontend/next.json'
export { default as _3dLibraries } from './frontend/three_d_libraries.json'
export { default as uilibraries } from './frontend/ui_libraries.json'
export { default as jsChartLibraries } from './frontend/js_chart_libraries.json'


//ai tools
export { default as design } from './ai_tools/design.json'
export { default as blog_writing } from './ai_tools/blog_writing.json'
export { default as chat_bots } from './ai_tools/chat_bots.json'
export { default as tensorflow } from './ai_tools/tensorflow.json'
